### ISSUE TITLE
mentionDenotationChars not functioning as allowedChars

### ISSUE THREAD

**Issue by onasman** [quill-mention/quill-mention#229] opened 2021-12-06 22:07 UTC
Currently "@" and other mentionDenotationChars are not functioning as allowedChar as it re-triggers the mention module. This causes issues when you for instance want to search in your data by email as it closes the search box once you type "@". Would be great with an exception that looks in allowedChars before deciding to close the search pop up.

**Comment by blahbleepew** [comment] 2022-10-17 17:51
is there a solution to this?

**Comment by MadSpindel** [comment] 2023-07-16 11:01
Duplicate of #177

**Closed by MadSpindel** 2023-07-16 11:01 UTC
