### ISSUE TITLE
quill-mention should support Quill Version 2.0.0-rc.0

### ISSUE THREAD

**Issue by devaman** [quill-mention/quill-mention#361] opened 2024-02-07 07:48 UTC
Issues found : 
- mentionDenotationChars when inserted at start of text is not opening the Dropdown
- After Selecting a value from dropdown and hitting enter is adding a new line in editor instead of inserting an embed

**Comment by csculley** [comment] 2024-03-12 14:11
Marking as a duplicate of #362 even though this one is a bit older because I am blind 😅

**Comment by xie392** [comment] 2024-03-14 04:05
> Issues found :
> 
> * mentionDenotationChars when inserted at start of text is not opening the Dropdown
> * After Selecting a value from dropdown and hitting enter is adding a new line in editor instead of inserting an embed

I wrote a simple implementation for my own use. You can [click to see it](https://github.com/xie392/quill-mention-react) it may be helpful to you.

**Closed** 2024-05-03 15:17 UTC
Labels: duplicate
